use crate::error::{Result, YtdError};
use crate::paths::YtdPaths;
use fs2::FileExt;
use std::fs::OpenOptions;
use std::io::Write;
use std::process::Command;
use std::time::{Duration, SystemTime};

const COOKIE_MAX_AGE_SECS: u64 = 1800;

const COOKIE_EXPORT_SCRIPT: &str = r###"
import http.cookiejar
import sys

try:
    import browser_cookie3
except Exception as exc:
    print(f"browser_cookie3 import failed: {exc}", file=sys.stderr)
    sys.exit(2)

cookie_path = sys.argv[1]
loaders = []
for name in ("chrome", "chromium", "brave", "edge"):
    loader = getattr(browser_cookie3, name, None)
    if loader is not None:
        loaders.append((name, loader))

jar = None
last_error = None
for _, loader in loaders:
    try:
        jar = loader()
        if jar:
            break
    except Exception as exc:
        last_error = exc

if jar is None:
    print(f"Unable to read browser cookies: {last_error}", file=sys.stderr)
    sys.exit(3)

with open(cookie_path, "w", encoding="utf-8") as handle:
    handle.write("# Netscape HTTP Cookie File\n")
    handle.write("# Generated by YutubuDownload\n")
    for cookie in jar:
        domain = cookie.domain or ""
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = cookie.path or "/"
        secure = "TRUE" if cookie.secure else "FALSE"
        expires = str(int(cookie.expires)) if cookie.expires else "0"
        name = cookie.name or ""
        value = cookie.value or ""
        handle.write("\t".join([domain, include_subdomains, path, secure, expires, name, value]) + "\n")
"###;

pub fn cookie_store_is_fresh(paths: &YtdPaths) -> bool {
    let Ok(meta) = std::fs::metadata(&paths.cookie_file) else {
        return false;
    };
    if meta.len() == 0 {
        return false;
    }
    let Ok(modified) = meta.modified() else {
        return false;
    };
    let Ok(age) = SystemTime::now().duration_since(modified) else {
        return false;
    };
    age < Duration::from_secs(COOKIE_MAX_AGE_SECS)
}

fn python_candidates(paths: &YtdPaths) -> Vec<String> {
    let mut candidates = vec![
        "python3".to_string(),
        "python".to_string(),
        paths.venv_python().to_string_lossy().into_owned(),
    ];
    candidates.sort();
    candidates.dedup();
    candidates
}

const COOKIE_EXPORT_TIMEOUT_SECS: u64 = 10;

fn export_shared_cookies(paths: &YtdPaths) -> Result<()> {
    paths.ensure_dirs()?;
    let cookie_path = paths.cookie_file.to_string_lossy().to_string();

    for python in python_candidates(paths) {
        let python = python.clone();
        let cookie_path = cookie_path.clone();
        let output = std::thread::scope(|scope| {
            let (tx, rx) = std::sync::mpsc::channel();
            scope.spawn(move || {
                let out = Command::new(&python)
                    .arg("-c")
                    .arg(COOKIE_EXPORT_SCRIPT)
                    .arg(&cookie_path)
                    .output();
                let _ = tx.send(out);
            });
            rx.recv_timeout(Duration::from_secs(COOKIE_EXPORT_TIMEOUT_SECS))
                .ok()
        });

        match output {
            Some(Ok(out)) if out.status.success() => {
                #[cfg(unix)]
                {
                    use std::os::unix::fs::PermissionsExt;
                    if let Ok(meta) = std::fs::metadata(&paths.cookie_file) {
                        let mut perms = meta.permissions();
                        perms.set_mode(0o600);
                        let _ = std::fs::set_permissions(&paths.cookie_file, perms);
                    }
                }
                return Ok(());
            }
            Some(Ok(out)) => {
                let _stderr = String::from_utf8_lossy(&out.stderr);
            }
            Some(Err(_)) | None => continue,
        }
    }

    Err(YtdError::Cookie(
        "No working Python with browser_cookie3 found".into(),
    ))
}

fn write_fallback_cookies(paths: &YtdPaths) -> Result<()> {
    paths.ensure_dirs()?;
    let mut file = OpenOptions::new()
        .create(true)
        .write(true)
        .truncate(true)
        .open(&paths.cookie_file)?;
    writeln!(file, "# Netscape HTTP Cookie File")?;
    writeln!(
        file,
        "# Generated by YutubuDownload (fallback - no browser cookies)"
    )?;
    Ok(())
}

pub fn refresh_cookie_store(paths: &YtdPaths, force: bool) -> Result<String> {
    paths.ensure_dirs()?;
    std::fs::create_dir_all(paths.cookie_lock_file.parent().unwrap_or(&paths.state_dir))?;

    let lock_file = OpenOptions::new()
        .create(true)
        .read(true)
        .write(true)
        .open(&paths.cookie_lock_file)?;

    lock_file.lock_exclusive()?;

    if !force && cookie_store_is_fresh(paths) {
        fs2::FileExt::unlock(&lock_file)?;
        return Ok("Cookies already fresh".into());
    }

    let message = match export_shared_cookies(paths) {
        Ok(()) => "Shared cookies ready".to_string(),
        Err(_) => {
            write_fallback_cookies(paths)?;
            "Fallback empty cookies file ready (browser export failed)".to_string()
        }
    };

    fs2::FileExt::unlock(&lock_file)?;
    Ok(message)
}

pub fn ensure_cookie_store(paths: &YtdPaths) -> Result<()> {
    paths.ensure_dirs()?;
    if paths.cookie_file.is_file() {
        return Ok(());
    }
    write_fallback_cookies(paths)
}
